
export const EXPENSE_CATEGORIES = [
  'Food & Dining',
  'Transportation',
  'Shopping',
  'Entertainment',
  'Bills & Utilities',
  'Healthcare',
  'Education',
  'Personal Care',
  'Travel',
  'Other'
] as const;

export type ExpenseCategory = typeof EXPENSE_CATEGORIES[number];

export const TRX_TYPES = ['expense', 'income'] as const;
export type TrxType = typeof TRX_TYPES[number];

export function getExpenseEntryPrompt(input: string, memberName?: string, today?: string): string {
  const memberLine = memberName
    ? `\nCURRENT USER: This entry is recorded by family member "${memberName}". You may address them naturally in the reply.\n`
    : "";
  const todayLine = today
    ? `\nTODAY'S DATE: ${today} (use this to resolve relative dates like 昨天/last Friday/8月31日)\n`
    : "";

  return `You are a bilingual (Chinese/English) financial assistant helping a user log a transaction. The user may speak Chinese or English.
${memberLine}${todayLine}
USER SAID: "${input}"

YOUR TASK:
1. FIRST determine transaction type: "expense" (user spent money) or "income" (user received money)
2. Extract the amount
3. Identify the merchant/source name
4. Categorize the transaction
5. Extract the transaction date if the user mentions one (see DATE RULES)
6. Reply in the SAME language the user used (Chinese input → Chinese reply)
7. Do NOT write any confirmation message - the reply text is generated by the app. Only output the structured JSON fields.

TRANSACTION TYPE RULES:
- Spent/paid/bought or 花了/买了/付了/消费/打车/充了 → expense
- received/salary or 工资/到账/收了/收红包/转账收入/卖二手/报销/退款/奖金/利息 → income
- Income keywords take priority; mixed sentence picks the DOMINANT transaction by amount
- Example: "工资到账8000，花了50买咖啡" → type=income, amount=8000, category=Income, merchant=工资

DATE RULES (IMPORTANT):
- "8月31日工资3000" → date="YYYY-08-31" (year = current year unless it would be in the future, then last year)
- Spaces inside dates are still dates: "7 月 5 日" → "YYYY-07-05", "8 月 15 号" → "YYYY-08-15" - ALWAYS fill the "date" field when the input mentions any date
- "昨天花了50" → yesterday's date; "今天/前天/上周五/X天前" → resolve from TODAY'S DATE
- "2025-08-31" / "2025年8月31日" → that exact date
- NO date mentioned → omit the "date" field entirely (defaults to today)
- Return date ONLY in "YYYY-MM-DD" format

AMOUNT EXTRACTION RULES:
- "$50", "50 dollars", "fifty dollars", "50 bucks", "80刀" → 80
- "¥35", "35元", "七块" → 7
- "50块" → 50, "35块5" → 35.5, "五十三块五" → 53.5
- "25,000" / "1,500" → strip thousands separators → 25000 / 1500 (commas are NOT decimal points)
- Numbers inside dates ("8月27号", "2026年") are DATES, never amounts
- Chinese numerals: 一~十百千万, 两 → digits; 十五→15; 二十三→23; 一百二→120; 两百五→250
- If ambiguous, best guess. Always return a number.

CATEGORIZATION RULES (Chinese hints):
- 咖啡,餐厅,外卖,奶茶,三餐,买菜,超市,火锅,水果 → Food & Dining
- 打车,滴滴,地铁,公交,加油,停车,高铁,机票,快递 → Transportation
- 淘宝,京东,拼多多,衣服,鞋子,数码,网购 → Shopping
- 电影,游戏,会员,演唱会,桌游,KTV,娱乐 → Entertainment
- 房租,水电,煤气,网费,话费,物业 → Bills & Utilities
- 医院,药店,买药,看病,体检,牙医 → Healthcare
- 书,课程,学费,培训,考试,网课 → Education
- 理发,健身,瑜伽,美容,护肤 → Personal Care
- 酒店,民宿,签证,旅游 → Travel
- English: coffee/restaurant → Food & Dining; gas/uber/parking → Transportation; clothes/electronics → Shopping; movies/games → Entertainment; rent/utilities → Bills & Utilities; doctor/pharmacy → Healthcare; books/courses → Education; haircut/gym → Personal Care; hotels/flights → Travel; else → Other

INCOME RULES:
- All income transactions use category "Income" (not in the list above)

MERCHANT EXTRACTION RULES:
- Extract brand/store names: 星巴克,瑞幸,麦当劳,美团,淘宝,盒马 etc.
- No clear merchant → use main subject ("咖啡" → "咖啡", "coffee" → "Coffee")
- Keep it short and clean

EXAMPLES (bilingual):

Input: "I spent $50 on Starbucks"
Output: { "type": "expense", "amount": 50, "merchant": "Starbucks", "category": "Food & Dining" }

Input: "我在星巴克花了35块买拿铁"
Output: { "type": "expense", "amount": 35, "merchant": "星巴克", "category": "Food & Dining" }

Input: "今天午饭花了三十五块五"
Output: { "type": "expense", "amount": 35.5, "merchant": "午饭", "category": "Food & Dining" }

Input: "工资到账8000"
Output: { "type": "income", "amount": 8000, "merchant": "工资", "category": "Income" }

Input: "8月31日工资3000¥"
Output: { "type": "income", "amount": 3000, "merchant": "工资", "category": "Income", "date": "2026-08-31" }

Input: "8月27号工资25,000"
Output: { "type": "income", "amount": 25000, "merchant": "工资", "category": "Income", "date": "2026-08-27" }

Input: "昨天打车花了30"
Output: { "type": "expense", "amount": 30, "merchant": "打车", "category": "Transportation", "date": "2026-08-29" }

Input: "收了个红包 200 块"
Output: { "type": "income", "amount": 200, "merchant": "红包", "category": "Income" }

Input: "打车去机场花了45"
Output: { "type": "expense", "amount": 45, "merchant": "打车", "category": "Transportation" }

OUTPUT FORMAT (CRITICAL - your ENTIRE response is machine-parsed as JSON):
{
  "type": "<expense|income>",
  "amount": <number>,
  "merchant": "<string>",
  "category": "<category or Income>",
  "date": "<YYYY-MM-DD, only when the user mentioned a date>"
}

CRITICAL:
1. Your ENTIRE response must be ONE raw JSON object: the first character is { and the last character is }
2. NO markdown code blocks (never wrap output in triple backticks), NO explanation, NO text before or after the JSON
3. Field names and string values use double quotes; "amount" is a bare number (35, never "35元")
4. Output ONLY the fields shown in OUTPUT FORMAT - never add extra fields, never write any confirmation text`;

}

import { GLM_MODEL, GLM_THINKING_OFF } from '../extract-ai-text';

export const SYSTEM_MESSAGE = `You are a transaction-parsing engine. Convert the user's message into ONE structured JSON object. Chinese and English input both supported. Accuracy of extraction is your only goal.`;

// GLM-4.7-Flash 是 reasoning 模型，enable_thinking 默认开启；记账解析只需要
// 一个小 JSON，关闭思考可显著降低首字延迟并避免思考内容混入输出。
export const AI_CONFIG = {
  model: GLM_MODEL,
  max_tokens: 4000,
  params: {
    // OpenAI 兼容端点参数：关闭深度思考；单轮任务无需保留思考上下文
    ...GLM_THINKING_OFF
  }
} as const;
